config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :decks, :only => [:new, :create, :show]

  root 'site#index'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :name, :presence => true
  validates :url, :format => {:with => URI::regexp(%w(http https)), :message => "must be a valid"}
  validates :url, :format => {:with => /docs\.google\.com/, :message => "must be a Google Docs URL"}

  belongs_to :user

  def google_doc_id
    @google_doc_id ||= url.split("/d/").last.split("/").first.strip
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!

  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      redirect_to @deck
    else
      render :new
    end
  end

  def show
    @deck = Deck.find(params[:id])
  end

  private
    def deck_params
      params.require(:deck).permit(:name, :url)
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  # layout 'public'
  #
  # # GET /resource/sign_in
  # def new
  #   raise "stop".inspect
  #   render :layout => "public"
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/decks/new.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Upload a New Deck</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <%= form_for(@deck, :role => "form") do |f| %>
          <div class="form-group">
            <%= f.label :name, :class => "control-label" %>
            <%= f.text_field :name, :class => "form-control" %>
            <% if @deck.errors[:name].any? %>
            <p class="help-block-error"><%= @deck.errors.full_messages_for(:name).to_sentence %></p>
            <% else %>
            <p class="help-block">Any name will do, try not to name the deck after the content but rather something random.</p>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :url, "Google Doc URL", :class => "control-label" %>
            <%= f.text_field :url, :class => "form-control" %>
            <% if @deck.errors[:url].any? %>
            <p class="help-block-error"><%= @deck.errors.full_messages_for(:url).to_sentence %></p>
            <% else %>
            <p class="help-block">Your deck must be publically viewable and published as a Google Doc</p>
            <% end %>
          </div>
          <%= f.submit "Upload Deck", :class => "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/decks/show.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= @deck.name %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <iframe src="https://docs.google.com/presentation/d/<%= @deck.google_doc_id %>/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Battledecks</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div id="wrapper">
    <%= render 'layouts/shared/navigation' %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "BattleDecks", root_path, :class => "navbar-brand" %>
  </div>
  <!-- /.navbar-header -->

  <%= render 'layouts/shared/navigation/utility' %>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <%#= render 'layout/shared/navigation/search' %>

        <li>
          <%= link_to "Upload a Deck", new_deck_path %>
        </li>

        <%#= render 'layout/shared/navigation/main' %>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/shared/navigation/_main.html.erb
<li>
  <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <li>
      <a href="flot.html">Flot Charts</a>
    </li>
    <li>
      <a href="morris.html">Morris.js Charts</a>
    </li>
  </ul>
  <!-- /.nav-second-level -->
</li>
<li>
  <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
</li>
<li>
  <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
</li>
<li>
  <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <li>
      <a href="panels-wells.html">Panels and Wells</a>
    </li>
    <li>
      <a href="buttons.html">Buttons</a>
    </li>
    <li>
      <a href="notifications.html">Notifications</a>
    </li>
    <li>
      <a href="typography.html">Typography</a>
    </li>
    <li>
      <a href="icons.html"> Icons</a>
    </li>
    <li>
      <a href="grid.html">Grid</a>
    </li>
  </ul>
  <!-- /.nav-second-level -->
</li>
<li>
  <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <li>
      <a href="#">Second Level Item</a>
    </li>
    <li>
      <a href="#">Second Level Item</a>
    </li>
    <li>
      <a href="#">Third Level <span class="fa arrow"></span></a>
      <ul class="nav nav-third-level">
        <li>
          <a href="#">Third Level Item</a>
        </li>
        <li>
          <a href="#">Third Level Item</a>
        </li>
        <li>
          <a href="#">Third Level Item</a>
        </li>
        <li>
          <a href="#">Third Level Item</a>
        </li>
      </ul>
      <!-- /.nav-third-level -->
    </li>
  </ul>
  <!-- /.nav-second-level -->
</li>
<li class="active">
  <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <li>
      <a class="active" href="blank.html">Blank Page</a>
    </li>
    <li>
      <a href="login.html">Login Page</a>
    </li>
  </ul>
  <!-- /.nav-second-level -->
</li>

app/views/layouts/shared/navigation/_search.html.erb
<li class="sidebar-search">
  <div class="input-group custom-search-form">
    <input type="text" class="form-control" placeholder="Search...">
    <span class="input-group-btn">
      <button class="btn btn-default" type="button">
        <i class="fa fa-search"></i>
      </button>
    </span>
  </div>
  <!-- /input-group -->
</li>

app/views/layouts/shared/navigation/_utility.html.erb
<ul class="nav navbar-top-links navbar-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <% if user_signed_in? %>
      <li>
        <%= link_to edit_user_password_path do %>
          <i class="fa fa-gear fa-fw"></i> Settings
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to destroy_user_session_path, :method => :delete do %>
          <i class="fa fa-sign-out fa-fw"></i> Logout
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to new_user_registration_path do %>
          <i class="fa fa-user fa-fw"></i> Register
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-sign-in fa-fw"></i> Login
        <% end %>
      </li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/site/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Blank</h1>
      </div>
    </div>
  </div>
</div>